root: on

parser: babel-eslint
parserOptions:
  ecmaVersion: 8
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: on
    impliedStrict: on
    jsx: on

extends: airbnb

plugins:
  - compat

env:
  browser: on
  commonjs: on
  es6: on
  shared-node-browser: on

settings:
  import/resolver:
    babel-module: {}

rules:
  compat/compat: 2
  react/jsx-filename-extension: 0
  react/react-in-jsx-scope: 0
